#DOLPHOT params
base_params = {'FitSky' : '2',
                'SigPSF' : '5.0',
                'FlagMask' : '4',
                'SecondPass' : '5',
                'PSFPhotIt' : '2',
                'ApCor' : '1',
                'FSat' : '0.999',
                'NoiseMult' : '0.1',
                'RCombine' : '1.5',
                'CombineChi' : '0',
                'MaxIT' : '25',
                'InterpPSFlib' : '1',
                'SigFindMult' : '0.85',
                'PSFPhot' : '1',
                'Force1' : '0',
                'SkySig' : '2.25',
                'SkipSky' : '1',
                'UseWCS' : '2',
                'PSFres' : '1',
                'PosStep' : '0.25',
                'NIRCAMvega' : '0'}

short_params = {'shift' : '0 0',
                'xform' :'1 0 0',
                'raper' : '2',
                'rchi' : '1.5',
                'rsky0' : '15',
                'rsky1' : '35',
                'rsky2' : '3 10',
                'rpsf' : '15',
                'apsky' : '20 35'}

long_params = {'shift' : '0 0',
                'xform' :'1 0 0',
                'raper' : '3',
                'rchi' : '2.0',
                'rsky0' : '15',
                'rsky1' : '35',
                'rsky2' : '4 10',
                'rpsf' : '15',
                'apsky' : '20 35'}